server:
  port: 8080

spring:
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: session-observability
    description: Demo microservizio per observability con sessioni e MDC logging
    version: 0.0.1-SNAPSHOT
    java-version: 21
    spring-boot-version: 3.4.4
